### ISSUE TITLE
Unable to Clone

### ISSUE THREAD

**Issue by Poor-Him** [fdac23/news#3]
I am unable to clone anything into the container.
![image](https://github.com/fdac23/news/assets/89419007/246dca78-6c68-4676-bd91-d4f9ed7b8032)

**Comment by cgraha37** [comment]
I'm having a similar issue except it's saying "Bad owner or permissions"
![Screenshot 2023-09-05 115119](https://github.com/fdac23/news/assets/88526761/2d5a3610-3f0c-4635-9320-e58727d447ba)

**Comment by Manan-dev** [comment]
> I'm having a similar issue except it's saying "Bad owner or permissions" ![Screenshot 2023-09-05 115119](https://user-images.githubusercontent.com/88526761/265756016-2d5a3610-3f0c-4635-9320-e58727d447ba.jpg)

Try this, `chmod -R og-rwx ~/.ssh`

**Comment by audrism** [comment]
> I am unable to clone anything into the container. ![image](https://user-images.githubusercontent.com/89419007/265753913-246dca78-6c68-4676-bd91-d4f9ed7b8032.png)

You have:
host github
        User Poor-Him
        HostName github.com
        IdentitiesOnly yes
        IdentityFile ~/.ssh/id_ed25519


User should be git

**Comment by audrism** [comment]
> I'm having a similar issue except it's saying "Bad owner or permissions" ![Screenshot 2023-09-05 115119](https://user-images.githubusercontent.com/88526761/265756016-2d5a3610-3f0c-4635-9320-e58727d447ba.jpg)

cat .ssh/config
host github
          User cgraha37
          HostName github.com
          IdentitiesOnly yes
          IdentityFile ~/.ssh/id_rsa


Also, your key is not there:
ls .ssh 
authorized_keys  config  known_hosts

**Comment by audrism** [comment]
> > I'm having a similar issue except it's saying "Bad owner or permissions" ![Screenshot 2023-09-05 115119](https://user-images.githubusercontent.com/88526761/265756016-2d5a3610-3f0c-4635-9320-e58727d447ba.jpg)
> 
> Try this, `chmod -R og-rwx ~/.ssh`

yuu are not using your port, see the username

**Comment by audrism** [comment]
> > > I'm having a similar issue except it's saying "Bad owner or permissions" ![Screenshot 2023-09-05 115119](https://user-images.githubusercontent.com/88526761/265756016-2d5a3610-3f0c-4635-9320-e58727d447ba.jpg)
> > 
> > 
> > Try this, `chmod -R og-rwx ~/.ssh`
> 
> yuu are not using your port, see the username

If you use correct port, there is n .ssh/config
ls -ltr .ssh 
total 44
-rw-------. 1 mpatel65 mpatel65  411 Aug 31 19:02 id_ed25519
-rw-r--r--. 1 mpatel65 mpatel65  103 Aug 31 19:02 id_ed25519.pub
-rwx------. 1 mpatel65 mpatel65 1719 Sep  4 23:43 authorized_keys
-rw-r--r--. 1 mpatel65 mpatel65  888 Sep  5 14:27 known_hosts

**Comment by cgraha37** [comment]
> > > I'm having a similar issue except it's saying "Bad owner or permissions" ![Screenshot 2023-09-05 115119](https://user-images.githubusercontent.com/88526761/265756016-2d5a3610-3f0c-4635-9320-e58727d447ba.jpg)
> > 
> > 
> > Try this, `chmod -R og-rwx ~/.ssh`
> 
> yuu are not using your port, see the username

I'm not sure what you mean.

**Comment by audrism** [comment]
> > > I'm having a similar issue except it's saying "Bad owner or permissions" ![Screenshot 2023-09-05 115119](https://user-images.githubusercontent.com/88526761/265756016-2d5a3610-3f0c-4635-9320-e58727d447ba.jpg)
> > 
> > 
> > Try this, `chmod -R og-rwx ~/.ssh`
> 
> yuu are not using your port, see the username

/home/cgraha37 is not your home folder.
