### ISSUE TITLE
Docker not working

### ISSUE THREAD

**Issue by jking148** [fdac23/news#4]
When trying to connect to the docker container, I am unable to sign into the docker container using my password. Last night I was getting a permission denied, but today I am not given the option to input a password and I am getting this error message `Connection closed by 160.36.59.136 port 7763`. I have confirmed that my ssh key is getting accepted by the server but I am still unable to log in.

![image](https://github.com/fdac23/news/assets/123468360/a0f150db-0fe9-400a-a9c1-ce94cd71e19e)

**Comment by zac-perry** [comment]
I am also getting the exact same error. (netid: zperry4)

**Comment by LoganOneal** [comment]
The public key for my user in students.yml is different than the one I uploaded to github.

**Comment by sarhuang** [comment]
I'm confused on the Username. If I put my netid (shuang24), the connection closes. If I use something else, it asks for a password.
`Connection closed by 160.36.59.136 port 7748`

**Comment by alay10** [comment]
I'm getting the same error (netid: alay10)

**Comment by LSmith2174** [comment]
I am getting a time out message when connecting `ssh: connect to host da3.eecs.utk.edu port 7791: Connection timed out` (netid: lsmit248)

**Comment by audrism** [comment]
@jking148 fixed, please try

**Comment by audrism** [comment]
@ZacPerry-dev  fixed, please try

**Comment by audrism** [comment]
@sarhuang fixed, please try

**Comment by audrism** [comment]
@alay10 fixed please try

**Comment by audrism** [comment]
@LSmith2174 fixed, please try

**Comment by audrism** [comment]
@LoganOneal fixed, please try

**Comment by audrism** [comment]
`

**Comment by audrism** [comment]
> 

please use netid as username

**Comment by lvswann** [comment]
I get the error 'ssh: connect to host da3.eecs.utk.edu port 7788: No route to host' when I try to ssh with the config file and directly. (netid: lswann)

**Comment by audrism** [comment]
@lvswann started a container for you: please try
