### ISSUE TITLE
Password denied

### ISSUE THREAD

**Issue by jhulen** [fdac23/news#5]
When trying to connect to the container, my password isn't accepted. I'm using my UTK password. 

<img width="509" alt="Screenshot 2023-09-05 at 12 09 11 PM" src="https://github.com/fdac23/news/assets/112642997/969880a3-1bc1-47cf-a57a-a92d87795796">

**Comment by audrism** [comment]
Fixed, please try

**Comment by jhulen** [comment]
It works, thanks
